version: '3.1'

services:
 web:
    build: .
    depends_on:
      - test
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
 test:
   container_name: test
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   ports:
     - 3389:3306
   environment:
     MYSQL_ROOT_PASSWORD: 77777
     MYSQL_DATABASE: abarrotes
     MYSQL_USER: root
     MYSQL_PASSWORD: 77777